### PR TITLE
Naming policies for snake_case and kebab-case

### PR DESCRIPTION
**Pull request by vova-lantsov-dev**

### CODE REVIEW

**Comment by vova-lantsov-dev** [comment]
@mcatanzariti please add support for `netstandard2.0` build of `Dahomey.Json` to GitHub workflows. This test project targets `netcoreapp2.1`.

**Comment by vova-lantsov-dev** [comment]
I run netstandard2.0 tests locally, everything passed

**Comment by mcatanzariti** [comment]
nice feature thank you!

**Comment by mcatanzariti** [comment]
This folder src/Dahomey.Json.Tests.NetStandard2_0 should be removed, official test projects now supports multiple targets (.net core 2.1, 2.2, 3.0 & 3.1)
new tests sould be moved to official test folder

**Comment by vova-lantsov-dev** [comment]
@mcatanzariti I gonna do this

**Comment by vova-lantsov-dev** [comment]
@mcatanzariti done

**Pull request merged**
